name: simpleai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=25.1.1
  - packaging
  - numpy=1.26.4
  - siphash24
  - pyopencl
  - pygit2=1.15.1
  - psutil=6.0.0
  - httpx=0.27.0
  - PyYAML=6.0.1
  - tqdm=4.66.4
  - anyio
